---
apiVersion: v1
kind: Namespace
metadata:
  name: beta

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beta
  labels:
    project: free5gc
  namespace: beta
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/centos/volume2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8worker4
