apiVersion: v1
data:
  HTTP_PROXY: http://10.213.86.130:3128
  HTTPS_PROXY: http://10.213.86.130:3128
  NO_PROXY: localhost,127.0.0.1,localaddress,.localdomain.com,.local,.cluster.local,.cluster.local.,.local.,10.40.0.0/16,10.96.0.0/12,192.168.0.0/16,172.16.0.0/12
  http_proxy: http://10.213.86.130:3128
  https_proxy: http://10.213.86.130:3128
  no_proxy: localhost,127.0.0.1,localaddress,.localdomain.com,.local,.cluster.local,.cluster.local.,.local.,10.40.0.0/16,10.96.0.0/12,192.168.0.0/16,172.16.0.0/12
kind: ConfigMap
metadata:
  name: proxyconfig
  namespace: flux-system
